### ISSUE TITLE
License

### ISSUE THREAD

**Issue by redhog** [WebManifestation/shader-course#1]
Would you mind slapping some open source license on this, like the GPL 3, MIT or BSD?

**Comment by WebManifestation** [comment]
I never really thought about adding a license to any on my code yet. I'm just doing this to learn cool new things.

Do you really think I should attach a license it, also which one should I would pick?

**Comment by redhog** [comment]
Well, I think it's always good to attach a license so that people can reuse pieces if they end up learning stuff from it. More specifically, your mandelbrot fractal implementation was [suggested as a background for my window manager](https://github.com/redhog/InfiniteGlass/issues/50#issuecomment-604101462), and I can't include it unless it has a proper license.

If you don't really care, go with MIT. If you don't like companies taking advantage of code you've written without sharing their code in return, use GPL.

**Comment by WebManifestation** [comment]
I've made a new repo you can use. Licensed and everything!
I'll be working on the code here:
https://github.com/WebManifestation/mandelbrot-GLSL

**Comment by redhog** [comment]
Thanks :)
